version: "3"

services:

  app:
    image: bsielski/fantasy-names-generator-api:1.0.0
    #build:
      #context: ..
      #dockerfile: ./docker-production/Dockerfile
    expose:
      - 3000
    #volumes:
      #- assets:/usr/share/nginx/html
      #- configs:/etc/nginx/conf.d/default.conf
    env_file:
      - ./.env-app
      #- ./.env-webserver
    networks:
      - net-pg
      #- net-3000
      - default

  webserver:
    image: nginx:1.13.12-alpine
    volumes:
      #- assets:/usr/share/nginx/html
      #- configs:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8101
    networks:
      - rev-proxy
      - default
    depends_on:
      - app

networks:
  rev-proxy:
    external:
      name: rev-proxy
  net-pg:
    external:
      name: net-pg
