version: "3"

services:

  app:
    image: bsielski/fantasy-names-generator-api:1.0.0
    expose:
      - 3000
    #volumes:
      #- assets:/usr/share/nginx/html
      #- configs:/etc/nginx/conf.d/default.conf
    env_file: ./.env-app
    networks:
      - net-pg
      - default

  webserver:
    image: nginx:1.13.12-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: .env-webserver
    expose:
      - 8101
    networks:
      - rev-proxy
      - default
    depends_on:
      - app

networks:
  rev-proxy:
    external:
      name: rev-proxy
  net-pg:
    external:
      name: net-pg
