default: &default
  adapter: postgresql
  encoding: unicode
  host:  <%= ENV["POSTGRES_HOST"] %>
  port: 5432
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB_TEST"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB_PRODUCTION"] %>
