# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

@g1 = Group.create!(label: "Traditional Celtic names")

@g1a = Subgroup.create!(group: @g1)
@n1a1 = Nameset.create!(label: "Scottish male", subgroup: @g1a)
Name.create!(nameset: @n1a1, variants: "Boisil")
Name.create!(nameset: @n1a1, variants: "Feargan")
Name.create!(nameset: @n1a1, variants: "Taran")
@n1a2 = Nameset.create!(label: "Irish male", subgroup: @g1a)
Name.create!(nameset: @n1a2, variants: "Seanán")
Name.create!(nameset: @n1a2, variants: "Iarlugh")
Name.create!(nameset: @n1a2, variants: "Meallán")
@n1a3 = Nameset.create!(label: "Welsh male", subgroup: @g1a)
Name.create!(nameset: @n1a3, variants: "Angwyn")
Name.create!(nameset: @n1a3, variants: "Bryngwyn")
Name.create!(nameset: @n1a3, variants: "Maelmadog")

@g1b = Subgroup.create!(group: @g1)
@n1b1 = Nameset.create!(label: "Scottish female", subgroup: @g1b)
Name.create!(nameset: @n1b1, variants: "Brianag")
Name.create!(nameset: @n1b1, variants: "Fionnghuala")
Name.create!(nameset: @n1b1, variants: "Muireall")
@n1b2 = Nameset.create!(label: "Irish female", subgroup: @g1b)
Name.create!(nameset: @n1b2, variants: "Deirdre")
Name.create!(nameset: @n1b2, variants: "Muireann")
Name.create!(nameset: @n1b2, variants: "Sláine")
@n1b3 = Nameset.create!(label: "Scottish female", subgroup: @g1b)
Name.create!(nameset: @n1b3, variants: "Arwen")
Name.create!(nameset: @n1b3, variants: "Gwen")
Name.create!(nameset: @n1b3, variants: "Morwen")

g2 = Group.create!(label: "Traditional Germanic names")

g2a = Subgroup.create!(group: g2)
ns2a1 = Nameset.create!(label: "Anglo-Saxon male", subgroup: g2a)
Name.create!(nameset: ns2a1, variants: "Adulf")
Name.create!(nameset: ns2a1, variants: "Ulfbehrt")
Name.create!(nameset: ns2a1, variants: "Sigeric")
ns2a2 = Nameset.create!(label: "Frankish male", subgroup: g2a)
Name.create!(nameset: ns2a2, variants: "Einhard")
Name.create!(nameset: ns2a2, variants: "Nordbert")
Name.create!(nameset: ns2a2, variants: "Wulfram")
ns2a3 = Nameset.create!(label: "Gothic male", subgroup: g2a)
Name.create!(nameset: ns2a3, variants: "Ermanaric")
Name.create!(nameset: ns2a3, variants: "Sidimund")
Name.create!(nameset: ns2a3, variants: "Totila")
ns2a4 = Nameset.create!(label: "Norse male", subgroup: g2a)
Name.create!(nameset: ns2a4, variants: "Ivar")
Name.create!(nameset: ns2a4, variants: "Ulf")
Name.create!(nameset: ns2a4, variants: "Thrand")

g2b = Subgroup.create!(group: g2)
ns2b1 = Nameset.create!(label: "Anglo-Saxon female", subgroup: g2b)
Name.create!(nameset: ns2b1, variants: "Begilda")
Name.create!(nameset: ns2b1, variants: "Herburga")
Name.create!(nameset: ns2b1, variants: "Wendreda")
ns2b2 = Nameset.create!(label: "Frankish female", subgroup: g2b)
Name.create!(nameset: ns2b2, variants: "Bertha")
Name.create!(nameset: ns2b2, variants: "Hildegarde")
Name.create!(nameset: ns2b2, variants: "Oda")
ns2b3 = Nameset.create!(label: "Gothic female", subgroup: g2b)
Name.create!(nameset: ns2b3, variants: "Helchen")
Name.create!(nameset: ns2b3, variants: "Erelieva")
Name.create!(nameset: ns2b3, variants: "Sunigilda")
ns2b4 = Nameset.create!(label: "Norse female", subgroup: g2b)
Name.create!(nameset: ns2b4, variants: "Astrid")
Name.create!(nameset: ns2b4, variants: "Halldora")
Name.create!(nameset: ns2b4, variants: "Thola")

g3 = Group.create!(label: "Other traditional names")

g3a = Subgroup.create!(group: g3)
ns3a1 = Nameset.create!(label: "Finnish male", subgroup: g3a)
Name.create!(nameset: ns3a1, variants: "Ilkka")
Name.create!(nameset: ns3a1, variants: "Pellervo")
Name.create!(nameset: ns3a1, variants: "Varma")
ns3a2 = Nameset.create!(label: "Japanese male", subgroup: g3a)
Name.create!(nameset: ns3a2, variants: "Haruki")
Name.create!(nameset: ns3a2, variants: "Naoki")
Name.create!(nameset: ns3a2, variants: "Takeshi")
ns3a3 = Nameset.create!(label: "Indian male", subgroup: g3a)
Name.create!(nameset: ns3a3, variants: "Abhijvala")
Name.create!(nameset: ns3a3, variants: "Drsadvata")
Name.create!(nameset: ns3a3, variants: "Srinivas")

g3b = Subgroup.create!(group: g3)
ns3b1 = Nameset.create!(label: "Finnish female", subgroup: g3b)
Name.create!(nameset: ns3b1, variants: "Kaisla")
Name.create!(nameset: ns3b1, variants: "Mervi")
Name.create!(nameset: ns3b1, variants: "Ulpukka")
ns3b2 = Nameset.create!(label: "Japanese female", subgroup: g3b)
Name.create!(nameset: ns3b2, variants: "Emi")
Name.create!(nameset: ns3b2, variants: "Mitsuko")
Name.create!(nameset: ns3b2, variants: "Tamiko")
ns3b3 = Nameset.create!(label: "Indian female", subgroup: g3b)
Name.create!(nameset: ns3b3, variants: "Astha")
Name.create!(nameset: ns3b3, variants: "Kannika")
Name.create!(nameset: ns3b3, variants: "Sumitra")
